version: '3.3'

services:
    web:
        image: domano/memefy_server:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - meme_volume:/app/files
volumes:
    meme_volume: